name: .NET API CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_PATH: Identity.Api
  DOCKERHUB_USERNAME: samlearning1709
  IMAGE_NAME: identity-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      # The path is now relative to the repository root.
      run: dotnet restore ${{ env.PROJECT_PATH }}/${{ env.PROJECT_PATH }}.csproj

    - name: Build
      # The path is now relative to the repository root.
      run: dotnet build ${{ env.PROJECT_PATH }}/${{ env.PROJECT_PATH }}.csproj --no-restore

    - name: Run tests
      # The path is now relative to the repository root.
      run: dotnet test --no-build --verbosity normal

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
       # The 'context' is the path to the folder containing the Dockerfile.
       # It is now correctly pointing to the Identity.Api folder.
        context: ${{ env.PROJECT_PATH }}
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
